[package]
name = "neuromodoel"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.9.0-alpha.1", features = [ "small_rng" ] }
vec_to_array = "0.2.3"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
nd_array = "0.1.0"
